services:
  postges:
    container_name: ink-spell-postgres
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - path: apps/server/.env.local
        required: false
      - path: apps/server/.env.example
        required: false
