/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "forgot_password_request": string;
        "register_email_request": string;
        "incorrect_username_or_password": string;
        "token_expired": string;
        "code_error": string;
        "account_exists": string;
        "username_exists": string;
    };
    "common": {
        "author": string;
        "main_character": string;
        "description": string;
    };
    "prompt": {
        "refresh_successful": string;
        "login_successful": string;
        "acquire_successful": string;
        "added_successfully": string;
        "no_such_bookmark": string;
        "deleted_successfully": string;
        "collection_successful": string;
        "cancellation_successful": string;
        "followed_successfully": string;
        "reset_successful": string;
        "update_successful": string;
        "send_successful": string;
        "upload_successful": string;
        "note_download_failed": string;
        "no_book_title": string;
        "no_author": string;
        "no_main_character": string;
        "no_description": string;
        "server_error": string;
        "rate_successful": string;
    };
    "validation": {
        "already_collected_bookshelf": string;
        "already_followed": string;
        "incorrect_original_password": string;
        "no_matching_user_found": string;
        "account_not_found": string;
        "account_not_linked_to_email": string;
        "email_sending_failed": string;
        "bookshelf_name_taken": string;
        "password_cannot_contain_spaces": string;
        "new_password_cannot_contain_spaces": string;
        "username_cannot_contain_spaces": string;
        "account_cannot_be_empty": string;
        "bookshelf_name_cannot_by_empty": string;
        "account_must_be_length_characters_long": string;
        "username_must_be_length_characters_long": string;
        "password_must_be_length_characters_long": string;
        "new_password_must_be_length_characters_long": string;
        "code_must_be_length_characters_long": string;
        "password_cannot_be_empty": string;
        "new_password_cannot_be_empty": string;
        "password_must_be_a_string": string;
        "new_password_must_be_a_string": string;
        "bookshelf_name_must_be_a_string": string;
        "avatar_must_be_a_string": string;
        "code_must_be_number": string;
        "email_format_invalid": string;
        "download_successful": string;
        "tag_exists": string;
        "username_cannot_be_empty": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
