export { default as coverImg } from './cover.png'
export { default as iconDarkImg } from './icon-dark.png'
export { default as iconLightImg } from './icon-light.png'
export { default as imageLoadingImg } from './image-loading.png'
export { default as loginDarkImg } from './login-dark.png'
export { default as loginLightImg } from './login-light.png'
export { default as logoDarkImg } from './logo-dark.png'
export { default as logoLightImg } from './logo-light.png'