-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "create_timer" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "BookShelf" ALTER COLUMN "create_timer" SET DEFAULT CURRENT_TIMESTAMP;
